# Generated by Django 5.2.10 on 2026-01-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this server', max_length=255, unique=True)),
                ('type', models.CharField(choices=[('stdio', 'Standard Input/Output (Subprocess)'), ('sse', 'Server-Sent Events (HTTP)')], default='stdio', max_length=10)),
                ('command', models.CharField(blank=True, help_text="Executable command (e.g., 'npx', 'python', 'docker')", max_length=1024, null=True)),
                ('args', models.JSONField(blank=True, default=list, help_text='List of arguments for the command')),
                ('url', models.URLField(blank=True, help_text='URL for SSE connection', null=True)),
                ('env', models.JSONField(blank=True, default=dict, help_text='Environment variables to pass to the server')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
