# Generated by Django 5.2.10 on 2026-04-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0002_add_credential_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcpserver',
            new_name='mcp_integra_enabled_3bb563_idx',
            old_name='mcp_integra_enabled_c3a5b9_idx',
        ),
    ]
