# Generated by Django 5.2.14 on 2026-08-13 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0007_add_slack_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='category',
            field=models.CharField(choices=[('google_workspace', 'Google Workspace'), ('communication', 'Communication'), ('productivity', 'Productivity'), ('development', 'Development'), ('utilities', 'Utilities'), ('custom', 'Custom')], default='custom', help_text='Grouping used by the Connections page', max_length=32),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name shown in the UI. Falls back to `name` when blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='help_url',
            field=models.URLField(blank=True, help_text='Link to provider docs for obtaining credentials'),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='icon_slug',
            field=models.CharField(blank=True, help_text="Stable icon identifier the frontend maps to an icon component (e.g. 'gmail')", max_length=64),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='tagline',
            field=models.CharField(blank=True, help_text='One-line plain-language description of what this connection enables', max_length=255),
        ),
        migrations.CreateModel(
            name='MCPServerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='mcp_integration.mcpserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_server_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'enabled'], name='mcp_integra_user_id_a1a5e2_idx')],
                'unique_together': {('user', 'server')},
            },
        ),
    ]
