# Generated by Django 5.2.14 on 2026-08-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0012_enable_gmail_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='credential_file_map',
            field=models.JSONField(blank=True, default=dict, help_text='Maps env var name -> {"filename", "target", "content"}. The content is rendered with the same {slug:field} placeholders as credential_header_map and written to a per-user temp file; the env var receives its path (target="file") or its directory (target="dir"). For servers that read credentials from disk.'),
        ),
    ]
