# Generated by Django 5.2.14 on 2026-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0014_enable_google_file_connectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='credential_header_map',
            field=models.JSONField(blank=True, default=dict, help_text='Maps HTTP header name -> value (may contain {slug:field} placeholders). Used for http/sse.'),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='type',
            field=models.CharField(choices=[('stdio', 'Standard Input/Output (Subprocess)'), ('http', 'Streamable HTTP'), ('sse', 'Server-Sent Events (HTTP, deprecated)')], default='stdio', max_length=10),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='url',
            field=models.URLField(blank=True, help_text='Endpoint for a remote server (streamable HTTP or SSE)', null=True),
        ),
    ]
