# Generated by Django 5.2.14 on 2026-09-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0015_alter_mcpserver_credential_header_map_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPOAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.URLField(help_text='Authorization server issuer URL')),
                ('redirect_uri', models.URLField(help_text='Redirect URI this client was registered for')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.BinaryField(blank=True, help_text='Fernet-encrypted client secret, when the server issues one', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('issuer', 'redirect_uri')},
            },
        ),
        migrations.CreateModel(
            name='MCPOAuthFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('code_verifier', models.CharField(max_length=255)),
                ('redirect_uri', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcp_integration.mcpoauthclient')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcp_integration.mcpserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCPOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.BinaryField(help_text='Fernet-encrypted access token')),
                ('refresh_token', models.BinaryField(blank=True, help_text='Fernet-encrypted refresh token', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcp_integration.mcpoauthclient')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='mcp_integration.mcpserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_oauth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'server'], name='mcp_integra_user_id_ca5215_idx')],
                'unique_together': {('user', 'server')},
            },
        ),
    ]
