# Generated by Django 5.2.14 on 2026-09-13 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0017_coming_soon_connectors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToolCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.JSONField(default=list)),
                ('listed_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_catalogues', to='mcp_integration.mcpserver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_catalogues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'user'], name='mcp_integra_server__1f4966_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('server', 'user'), name='uniq_mcp_catalogue_per_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('server',), name='uniq_mcp_catalogue_system')],
            },
        ),
    ]
