# Generated by Django 5.2.14 on 2026-09-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_integration', '0022_docs_native'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToolPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('digest', models.CharField(blank=True, default='', max_length=64)),
                ('pending_digest', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('trusted', 'Trusted'), ('changed', 'Changed since approved'), ('quarantined', 'Held for review')], default='trusted', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_pins', to='mcp_integration.mcpserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'user'], name='mcp_integra_server__919c38_idx')],
                'constraints': [models.UniqueConstraint(fields=('server', 'user', 'tool_name'), name='uniq_mcp_tool_pin')],
            },
        ),
    ]
