# Generated by Django 5.2.14 on 2026-09-21 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('hibernated', 'Hibernated'), ('failed', 'Failed')], default='creating', max_length=12)),
                ('disk_gb', models.IntegerField(default=5)),
                ('egress_policy', models.CharField(default='bridge', max_length=12)),
                ('secret', models.CharField(blank=True, default='', max_length=64)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='One per user in v1. Destroyed with the account.', on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cmd', models.TextField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=12)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, default='', max_length=500)),
                ('timeout_s', models.IntegerField(default=21600)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='workspaces__user_id_1f1d76_idx'), models.Index(fields=['workspace', 'status'], name='workspaces__workspa_fa5ddb_idx')],
            },
        ),
    ]
