# Generated by Django 5.2.14 on 2026-09-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0024_agentstep_approval'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('before_hash', models.CharField(blank=True, default='', max_length=64)),
                ('after_hash', models.CharField(blank=True, default='', max_length=64)),
                ('diff', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_changes', to='logs.executionlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('repo_url', models.CharField(blank=True, default='', max_length=500)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=120)),
                ('workspace_path', models.CharField(help_text='Project root on the workspace disk, e.g. /home/user/projects/api', max_length=500)),
                ('github_secret_ref', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_code_project_per_user')],
            },
        ),
    ]
