# Generated by Django 5.2.13 on 2026-09-23 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_kind', models.CharField(choices=[('api', 'API'), ('data', 'Database')], max_length=8)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='One line, shown on the card. What it reaches, not how.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tool_config', models.JSONField(default=dict)),
                ('auth_shape', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('link', 'Anyone with the link'), ('platform', 'Everyone on the platform'), ('public', 'Anyone, including people without an account')], default='platform', max_length=10)),
                ('is_listed', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('install_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='datasources.apiconnection')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_tools', to=settings.AUTH_USER_MODEL)),
                ('data_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='datasources.dataconnection')),
            ],
            options={
                'ordering': ['-install_count', '-updated_at'],
                'indexes': [models.Index(fields=['visibility', 'is_listed'], name='datasources_visibil_9a3671_idx'), models.Index(fields=['author', 'tool_kind'], name='datasources_author__542457_idx')],
            },
        ),
    ]
