# Generated by Django 5.2.10 on 2026-01-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_workflow_average_duration_ms_workflow_is_cloneable_and_more'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtestresult',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='templates.workflowtemplate'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='parent_template',
            field=models.ForeignKey(blank=True, help_text='Template this workflow was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_workflows', to='templates.workflowtemplate'),
        ),
        migrations.DeleteModel(
            name='WorkflowTemplate',
        ),
    ]
