# Generated by Django 5.2.10 on 2026-02-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_credentialtype_service_identifier'),
        ('orchestrator', '0004_add_supervision_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='llm_credential',
            field=models.ForeignKey(blank=True, help_text='Credential to use for LLM API calls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_using_llm', to='credentials.credential'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='llm_model',
            field=models.CharField(blank=True, default='google/gemini-2.0-flash-exp:free', help_text='Specific model to use (provider-dependent)', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='llm_provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter (100+ models)'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('ollama', 'Ollama (Local)'), ('perplexity', 'Perplexity')], default='openrouter', help_text='LLM provider for AI features (workflow generation, suggestions)', max_length=30),
        ),
    ]
