# Generated by Django 5.2.10 on 2026-02-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_add_llm_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('state', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_states', to='orchestrator.workflow')),
            ],
            options={
                'verbose_name': 'Trigger State',
                'verbose_name_plural': 'Trigger States',
                'unique_together': {('workflow', 'node_id')},
            },
        ),
    ]
