# Generated by Django 5.2.10 on 2026-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_triggerstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='context',
            field=models.TextField(blank=True, help_text='Context for the AI Supervisor to understand the workflow goal and execution nuance.'),
        ),
    ]
