# Generated by Django 5.2.10 on 2026-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0007_workflow_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='context',
            field=models.TextField(blank=True, default='', help_text='Context for the AI Supervisor to understand the workflow goal and execution nuance.'),
        ),
    ]
