# Generated by Django 5.2.13 on 2026-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0008_alter_workflow_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='supervision_level',
            field=models.CharField(choices=[('error_only', 'Error Only (Recommended)'), ('full', 'Full Supervision'), ('failsafe', 'Failsafe Supervision'), ('none', 'No Supervision')], default='error_only', help_text='Level of orchestrator supervision. WARNING: "Full Supervision" increases API costs and system overhead.', max_length=20),
        ),
    ]
