# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Workflow name', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this workflow does')),
                ('nodes', models.JSONField(default=list, help_text='Array of node definitions')),
                ('edges', models.JSONField(default=list, help_text='Array of edge connections')),
                ('viewport', models.JSONField(blank=True, default=dict, help_text='Canvas viewport state (zoom, pan position)')),
                ('workflow_settings', models.JSONField(blank=True, default=dict, help_text='Workflow-level settings (timeout, retry config, etc.)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_template', models.BooleanField(default=False, help_text='Whether this workflow is a template')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for organizing workflows')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('execution_count', models.IntegerField(default=0, help_text='Total number of executions')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, help_text='Groups messages into conversations')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (tokens used, model, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, help_text='Workflow context if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='orchestrator.workflow')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Sequential version number')),
                ('label', models.CharField(blank=True, help_text='Optional label for this version', max_length=100)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('workflow_settings', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_versions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orchestrator.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Version',
                'verbose_name_plural': 'Workflow Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='HITLRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('node_id', models.CharField(blank=True, help_text='ID of the node requesting human input', max_length=100)),
                ('request_type', models.CharField(choices=[('approval', 'Approval Required'), ('clarification', 'Clarification Needed'), ('error_recovery', 'Error Recovery')], max_length=20)),
                ('title', models.CharField(help_text='Short title for the request', max_length=200)),
                ('message', models.TextField(help_text='Detailed message explaining what is needed')),
                ('options', models.JSONField(blank=True, default=list, help_text='Available options/choices for the user')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('answered', 'Answered'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('response', models.JSONField(blank=True, default=dict, help_text='User response data')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_seconds', models.IntegerField(default=300, help_text='Timeout in seconds (0 = no timeout)')),
                ('auto_action', models.CharField(blank=True, help_text='Action to take on timeout (e.g., approve, reject, skip)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitl_requests', to='logs.executionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitl_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HITL Request',
                'verbose_name_plural': 'HITL Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id'], name='orchestrato_request_45bb35_idx'), models.Index(fields=['user', 'status'], name='orchestrato_user_id_75f173_idx'), models.Index(fields=['execution', 'status'], name='orchestrato_executi_162ac1_idx'), models.Index(fields=['status', '-created_at'], name='orchestrato_status_8ca8bd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['user', 'status'], name='orchestrato_user_id_b66260_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['user', '-updated_at'], name='orchestrato_user_id_ee3007_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['status', '-updated_at'], name='orchestrato_status_f587d8_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_template', 'status'], name='orchestrato_is_temp_639ac7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['user', 'conversation_id'], name='orchestrato_user_id_4c5d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation_id', 'created_at'], name='orchestrato_convers_c6557c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['user', '-created_at'], name='orchestrato_user_id_6eb4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', '-version_number'], name='orchestrato_workflo_01a0c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowversion',
            unique_together={('workflow', 'version_number')},
        ),
    ]
