# Generated by Django 5.2.10 on 2026-01-25 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='average_duration_ms',
            field=models.IntegerField(blank=True, help_text='Average execution duration in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_cloneable',
            field=models.BooleanField(default=True, help_text='Whether this workflow can be cloned by the orchestrator'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_subworkflow_enabled',
            field=models.BooleanField(default=True, help_text='Allow this workflow to be used as a subworkflow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='max_nesting_depth',
            field=models.IntegerField(default=3, help_text='Maximum allowed nesting depth to prevent infinite recursion'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='modifiable_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of fields that can be safely modified during cloning'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='successful_executions',
            field=models.IntegerField(default=0, help_text='Total number of successful executions'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='total_executions',
            field=models.IntegerField(default=0, help_text='Total number of times this workflow has been executed'),
        ),
        migrations.CreateModel(
            name='WorkflowCloneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifications_applied', models.JSONField(default=dict, help_text='Diff of what changed during cloning')),
                ('reason', models.TextField(blank=True, help_text='Why this clone was created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clone_source', to='orchestrator.workflow')),
                ('cloned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='orchestrator.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('workflow_settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_test', 'Pending Test'), ('verified', 'Verified'), ('production', 'Production'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_duration_ms', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('modifiable_fields', models.JSONField(blank=True, default=list)),
                ('is_cloneable', models.BooleanField(default=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='orchestrator.workflowtemplate')),
            ],
            options={
                'ordering': ['-usage_count', '-success_rate'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='parent_template',
            field=models.ForeignKey(blank=True, help_text='Template this workflow was cloned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_workflows', to='orchestrator.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('error', 'Error')], max_length=20)),
                ('test_input', models.JSONField(default=dict, help_text='Synthetic input used during test')),
                ('test_output', models.JSONField(default=dict, help_text='Actual output received')),
                ('expected_output_schema', models.JSONField(blank=True, default=dict)),
                ('execution_time_ms', models.IntegerField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_node_id', models.CharField(blank=True, max_length=100)),
                ('schema_valid', models.BooleanField(default=False)),
                ('timeout_within_limit', models.BooleanField(default=False)),
                ('no_exceptions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='orchestrator.workflow')),
                ('workflow_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='orchestrator.workflowtemplate')),
            ],
        ),
    ]
