# Generated by Django 5.2.10 on 2026-02-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_alter_workflowtestresult_workflow_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='supervision_level',
            field=models.CharField(choices=[('error_only', 'Error Only (Recommended)'), ('full', 'Full Supervision'), ('none', 'No Supervision')], default='error_only', help_text='Level of orchestrator supervision. WARNING: "Full Supervision" increases API costs and system overhead.', max_length=20),
        ),
    ]
