# Generated by Django 5.2.8 on 2026-07-29 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', 'add_google_oauth_fields'),
        ('orchestrator', '0010_workflow_keyset_pagination_index'),
        ('templates', '0002_alter_workflowtemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='agent_context',
            field=models.JSONField(blank=True, default=dict, help_text='What the agent is given: connectors, knowledge base ids, skill ids, org/environment flags'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='guardrails',
            field=models.JSONField(blank=True, default=dict, help_text='autonomy, spend cap, egress policy, review agent'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='kind',
            field=models.CharField(choices=[('workflow', 'Workflow'), ('agent', 'Agent')], db_index=True, default='workflow', help_text='Whether this row is a node graph or an autonomous agent', max_length=12),
        ),
        migrations.AddField(
            model_name='workflow',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text="Portable requirements for sharing — what kind of connection/KB the agent needs, never the author's own row ids"),
        ),
        migrations.AddField(
            model_name='workflow',
            name='sandbox',
            field=models.JSONField(blank=True, default=dict, help_text='Execution envelope: file access, workdir, venv, cpu, memory'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='tool_grants',
            field=models.JSONField(blank=True, default=dict, help_text='Which tools the agent may call, e.g. {"codeExecution": true, "shell": false}'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='trigger',
            field=models.JSONField(blank=True, default=dict, help_text='How it is invoked, e.g. {"mode": "maintenance", "cron": "0 9 * * 1"}'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['user', 'kind', '-updated_at'], name='orchestrato_user_id_305150_idx'),
        ),
    ]
