# Generated by Django 5.2.14 on 2026-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_retire_unsupported_llm_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='llm_provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter (400+ models)'), ('nvidia', 'NVIDIA NIM'), ('openai', 'OpenAI'), ('ollama', 'Ollama (Local)')], default='openrouter', help_text='LLM provider for AI features (workflow generation, suggestions)', max_length=30),
        ),
    ]
