# Generated by Django 5.2.14 on 2026-08-18 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_seed_credential_types'),
        ('orchestrator', '0014_drop_dag_era_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this agent is for — shown when picking one to delegate to')),
                ('prompt', models.TextField(blank=True, default='', help_text='The specialisation: what this agent is, how it should work, and what a good result looks like. Becomes its system prompt.')),
                ('llm_provider', models.CharField(choices=[('openrouter', 'OpenRouter (400+ models)'), ('nvidia', 'NVIDIA NIM'), ('openai', 'OpenAI'), ('ollama', 'Ollama (Local)')], default='openrouter', max_length=30)),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('tool_grants', models.JSONField(blank=True, default=dict, help_text='Which capabilities this agent may use, e.g. {"webSearch": true}')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='Portable requirements for sharing — what kind of connection or KB it needs, never the row ids of whoever authored it')),
                ('guardrails', models.JSONField(blank=True, default=dict, help_text='autonomy, spend cap, max delegation depth, egress policy')),
                ('agent_context', models.JSONField(blank=True, default=dict, help_text='What it is given: connector ids, knowledge base ids, skill ids')),
                ('sandbox', models.JSONField(blank=True, default=dict, help_text='Execution envelope: file access, workdir, venv, cpu, memory')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='Contract the result must satisfy. Empty means prose.')),
                ('fanout', models.JSONField(blank=True, default=dict, help_text='How it parallelises, e.g. {"parallel": 4, "mode": "collect"}. Empty means a single sequential turn.')),
                ('allow_unattended', models.BooleanField(default=False, help_text='May run with nobody watching (schedule, webhook, event). Off by default: a trigger is a way for something other than the user to spend their model credits.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_template', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subagents_using_llm', to='credentials.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-agent',
                'verbose_name_plural': 'Sub-agents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='orchestrato_user_id_3e9c25_idx'), models.Index(fields=['user', '-updated_at'], name='orchestrato_user_id_e053b1_idx'), models.Index(fields=['user', '-updated_at', '-id'], name='orchestrato_user_id_fd65c0_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
