# Generated by Django 5.2.14 on 2026-08-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0016_migrate_agents_to_subagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='subagent',
            field=models.ForeignKey(blank=True, help_text='Sub-agent this conversation is about, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='orchestrator.subagent'),
        ),
    ]
