# Generated by Django 5.2.14 on 2026-08-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0017_add_subagent_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagent',
            name='runtime_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Turn-level knobs: temperature, recursiveContext, compaction, indexing, and the builder’s invocation mode.'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('schedule', 'Schedule'), ('webhook', 'Webhook'), ('event', 'Event')], db_index=True, max_length=12)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Mode-specific: {"cron": "0 9 * * 1"} or {"event": "run.completed"}')),
                ('goal', models.TextField(blank=True, default='', help_text='What the agent is asked to do when this fires.')),
                ('secret', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('overlap', models.CharField(choices=[('skip', 'Skip this firing'), ('queue', 'Run after the current one'), ('cancel', 'Cancel the running one')], default='skip', max_length=8)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='orchestrator.subagent')),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['enabled', 'mode', 'next_due_at'], name='orchestrato_enabled_e18312_idx'), models.Index(fields=['subagent', 'mode'], name='orchestrato_subagen_aaad92_idx')],
            },
        ),
    ]
