# Generated by Django 5.2.14 on 2026-08-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_remove_auditentry_logs_audite_workflo_ee038c_idx_and_more'),
        ('orchestrator', '0018_add_trigger_and_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
