# Generated by Django 5.2.14 on 2026-08-29 06:36

from django.db import migrations, models


def mark_existing_as_builder(apps, schema_editor):
    """Every schedule that already exists was created by the agent builder.

    `origin` defaults to `manual` for new rows, because the API is now a way to
    add schedules the builder does not own. But until this migration there was
    no such API path in use: `AgentSerializer.sync_schedule` was the only thing
    that ever wrote a schedule Trigger. Backfilling the truth here is what lets
    `sync_schedule` have one unambiguous rule instead of a read-time guess that
    cannot tell a legacy row from a deliberate one.
    """
    apps.get_model('orchestrator', 'Trigger').objects.filter(
        mode='schedule').update(origin='builder')


def unmark(apps, schema_editor):
    apps.get_model('orchestrator', 'Trigger').objects.update(origin='manual')



class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0019_remove_conversationmessage_workflow_delete_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trigger',
            name='last_outcome',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='trigger',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='trigger',
            name='origin',
            field=models.CharField(choices=[('builder', 'Agent builder'), ('manual', 'Added directly')], db_index=True, default='manual', max_length=8),
        ),
        migrations.AddField(
            model_name='trigger',
            name='queued_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['enabled', 'mode', 'queued_for'], name='orchestrato_enabled_7d97ff_idx'),
        ),
        migrations.RunPython(mark_existing_as_builder, unmark),
    ]
