# Generated by Django 5.2.14 on 2026-09-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0021_clear_legacy_connector_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(help_text='One line, shown on the card. What it does, not how.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='The longer pitch, shown on the install screen.')),
                ('config', models.JSONField(default=dict, help_text='Allow-listed AgentConfig snapshot — see agents/publishing.py')),
                ('requirements', models.JSONField(default=list, help_text='What the installer must supply, as kinds and never as ids')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('visibility', models.CharField(choices=[('platform', 'Everyone on the platform'), ('link', 'Anyone with the link')], default='platform', max_length=10)),
                ('is_listed', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('install_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_agents', to=settings.AUTH_USER_MODEL)),
                ('subagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to='orchestrator.subagent')),
            ],
            options={
                'verbose_name': 'Shared agent',
                'verbose_name_plural': 'Shared agents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_listed', 'visibility', '-updated_at'], name='orchestrato_is_list_58977a_idx'), models.Index(fields=['author', '-updated_at'], name='orchestrato_author__c7796f_idx')],
            },
        ),
    ]
