# Generated by Django 5.2.14 on 2026-09-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0022_sharedagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedagent',
            name='visibility',
            field=models.CharField(choices=[('link', 'Anyone with the link'), ('platform', 'Everyone on the platform'), ('public', 'Anyone, including people without an account')], default='platform', max_length=10),
        ),
    ]
