# Generated by Django 5.2.13 on 2026-09-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0026_executionlog_fallback_from_executionlog_model_used'),
        ('orchestrator', '0024_template_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLease',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=80)),
                ('expires_at', models.DateTimeField()),
                ('beat_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='trigger',
            name='last_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logs.executionlog'),
        ),
    ]
