# Generated by Django 5.2.13 on 2026-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0025_schedulerlease_trigger_last_execution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagent',
            name='llm_provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter (400+ models)'), ('nvidia', 'NVIDIA NIM'), ('openai', 'OpenAI'), ('ollama', 'Ollama (Local)'), ('opencode', 'OpenCode Zen (free models, your key)')], default='openrouter', max_length=30),
        ),
    ]
