# Generated by Django 5.2.8 on 2026-07-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inference', '0008_document_keyset_pagination_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fields', models.JSONField(default=list, help_text='The columns to fill')),
                ('source_kind', models.CharField(choices=[('upload', 'Manual upload'), ('gmail', 'Gmail'), ('gdrive', 'Google Drive')], default='upload', max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text='Label, folder or query the documents come from', max_length=300)),
                ('confidence_threshold', models.FloatField(default=0.8, help_text='Below this, a row is held for review rather than accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=300)),
                ('data', models.JSONField(default=dict, help_text='Field name -> extracted value')),
                ('field_confidence', models.JSONField(blank=True, default=dict, help_text='Field name -> confidence, so review can point at the cell')),
                ('confidence', models.FloatField(default=0.0, help_text='Lowest field confidence in the row')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('needs_review', 'Needs review'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], db_index=True, default='accepted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_rows', to='inference.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extractions', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='extraction.extractionschema')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='extractionschema',
            index=models.Index(fields=['user', '-updated_at'], name='extraction__user_id_5a384d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extractionschema',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='extractedrow',
            index=models.Index(fields=['schema', 'status'], name='extraction__schema__2140c3_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedrow',
            index=models.Index(fields=['schema', '-created_at'], name='extraction__schema__6b3544_idx'),
        ),
    ]
