# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this API key', max_length=100)),
                ('key', models.CharField(editable=False, help_text='The actual API key (shown once on creation)', max_length=64, unique=True)),
                ('key_prefix', models.CharField(editable=False, help_text='First 8 characters for identification', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_apikey_user_id_ea969f_idx'), models.Index(fields=['key'], name='core_apikey_key_8b1d45_idx'), models.Index(fields=['key_prefix'], name='core_apikey_key_pre_e29082_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of usage record')),
                ('compile_count', models.IntegerField(default=0, help_text='Number of workflow compilations', validators=[django.core.validators.MinValueValidator(0)])),
                ('execute_count', models.IntegerField(default=0, help_text='Number of workflow executions', validators=[django.core.validators.MinValueValidator(0)])),
                ('chat_count', models.IntegerField(default=0, help_text='Number of AI chat messages', validators=[django.core.validators.MinValueValidator(0)])),
                ('tokens_used', models.IntegerField(default=0, help_text='Total LLM tokens consumed', validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_used', models.IntegerField(default=0, help_text='Credits consumed this day', validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, help_text='Estimated API cost in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='core_usaget_user_id_b86d31_idx'), models.Index(fields=['-date'], name='core_usaget_date_f80315_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', help_text='User subscription tier', max_length=20)),
                ('compile_limit', models.IntegerField(default=10, help_text='Workflow compilations per minute', validators=[django.core.validators.MinValueValidator(0)])),
                ('execute_limit', models.IntegerField(default=5, help_text='Workflow executions per minute', validators=[django.core.validators.MinValueValidator(0)])),
                ('stream_connections', models.IntegerField(default=5, help_text='Maximum concurrent streaming connections', validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_remaining', models.IntegerField(default=100, help_text='API credits remaining', validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_used_total', models.IntegerField(default=0, help_text='Total credits used historically', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tier'], name='core_userpr_tier_1b2a57_idx'), models.Index(fields=['user', 'tier'], name='core_userpr_user_id_45fb6b_idx')],
            },
        ),
    ]
