# Generated by Django 5.2.10 on 2026-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='llm_credential_id',
            field=models.IntegerField(blank=True, help_text='Default credential ID for King Orchestrator', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(default='google/gemini-2.0-flash-exp:free', help_text='Global LLM model for internal AI reasoning', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_provider',
            field=models.CharField(default='openrouter', help_text='Global LLM provider for internal AI reasoning', max_length=30),
        ),
    ]
