# Generated by Django 5.2.13 on 2026-04-27 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_llm_credential_id_userprofile_llm_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='blue', help_text='Preferred accent color (e.g. blue, magenta)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_max_tokens',
            field=models.IntegerField(default=2048, help_text='Default max tokens for AI responses', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_temperature',
            field=models.FloatField(default=0.7, help_text='Default temperature for AI reasoning', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public display name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instance_name',
            field=models.CharField(default='AIAAS Instance', help_text='Name of the platform instance for this user', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', help_text='User preferred language code (e.g. en, es)', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User preferred timezone', max_length=50),
        ),
    ]
