# Generated by Django 5.2.8 on 2026-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(default='nvidia/llama-3.3-nemotron-super-49b-v1', help_text='Global LLM model for internal AI reasoning', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='llm_provider',
            field=models.CharField(default='nvidia', help_text='Global LLM provider for internal AI reasoning', max_length=30),
        ),
    ]
