# Generated by Django 5.2.14 on 2026-08-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_llm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(default='nvidia/nemotron-3-super-120b-a12b', help_text='Global LLM model for internal AI reasoning', max_length=150),
        ),
    ]
