# Generated by Django 5.2.14 on 2026-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vision_model',
            field=models.CharField(blank=True, default='nvidia/nemotron-nano-12b-v2-vl', help_text='Vision model asked about images the main model cannot see', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vision_provider',
            field=models.CharField(blank=True, default='nvidia', help_text='Provider for the vision witness model', max_length=50),
        ),
    ]
