# Generated by Django 5.2.14 on 2026-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_vision_model_userprofile_vision_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='llm_effort',
            field=models.CharField(blank=True, default='medium', help_text='Default reasoning effort (blank = let the model decide)', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(default='openrouter/free', help_text='Global LLM model for internal AI reasoning', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='llm_provider',
            field=models.CharField(default='openrouter', help_text='Global LLM provider for internal AI reasoning', max_length=30),
        ),
    ]
