# Generated by Django 5.2.14 on 2026-09-03 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_effort_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('profile', 'Who they are'), ('preference', 'How they like to work'), ('project', 'What they are working on'), ('context', 'Anything else worth remembering')], default='context', max_length=20)),
                ('source', models.CharField(default='agent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user memories',
                'ordering': ['category', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'category', '-updated_at'], name='core_userme_user_id_c6215e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'text'), name='unique_user_memory_text')],
            },
        ),
    ]
