# Generated by Django 5.2.14 on 2026-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usermemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordotp',
            name='target_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordotp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('password_change', 'Password Change'), ('email_change', 'Email Change')], max_length=32),
        ),
    ]
