# Generated by Django 5.2.14 on 2026-09-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_email_change_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_autonomy',
            field=models.CharField(default='ask', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
