# Generated by Django 5.2.14 on 2026-09-25 12:19
#
# Account security (docs/SECURITY_REVIEW_FIX_PLAN.md): the two profile fields
# behind S1 and S2, and S6 -- every stored API key replaced by its SHA-256.
# Existing keys keep working: authentication hashes what the client sends and
# compares hashes. The hashing cannot be undone, so reversing leaves them hashed.

import hashlib

from django.db import migrations, models


def hash_api_keys(apps, schema_editor):
    APIKey = apps.get_model('core', 'APIKey')
    for key in APIKey.objects.all().only('pk', 'key').iterator():
        APIKey.objects.filter(pk=key.pk).update(
            key=hashlib.sha256(key.key.encode('utf-8')).hexdigest())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_default_autonomy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tokens_valid_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(hash_api_keys, migrations.RunPython.noop),
    ]
