# Generated by Django 5.2.14 on 2026-08-29 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tool configuration',
                'indexes': [models.Index(fields=['user', 'enabled'], name='tools_confi_user_id_ac7f88_idx')],
                'unique_together': {('user', 'tool_name')},
            },
        ),
    ]
