# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Original filename', max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('md', 'Markdown'), ('docx', 'Word Document'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('content_text', models.TextField(blank=True, help_text='Extracted text content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Document metadata (title, author, etc.)')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of chunks created')),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('folder', models.CharField(blank=True, help_text='Virtual folder path for organization', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Position of this chunk in the document')),
                ('content', models.TextField(help_text='Text content of this chunk')),
                ('token_count', models.IntegerField(default=0, help_text='Number of tokens in this chunk')),
                ('start_char', models.IntegerField(default=0, help_text='Starting character position')),
                ('end_char', models.IntegerField(default=0, help_text='Ending character position')),
                ('page_number', models.IntegerField(blank=True, help_text='Page number if applicable', null=True)),
                ('embedding', models.BinaryField(blank=True, help_text='Vector embedding (stored as binary)', null=True)),
                ('embedding_model', models.CharField(blank=True, help_text='Model used for embedding', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Chunk-level metadata (headings, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='inference.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_id'], name='inference_d_documen_778bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='inference_d_user_id_75a81d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-created_at'], name='inference_d_user_id_5d4d20_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type', 'status'], name='inference_d_file_ty_a427ff_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='inference_d_documen_4ecf55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
