# Generated by Django 5.2.10 on 2026-01-22 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='If True, document is shared with platform knowledge base'),
        ),
        migrations.AddField(
            model_name='document',
            name='shared_at',
            field=models.DateTimeField(blank=True, help_text='When the document was shared with platform', null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_shared', 'status'], name='inference_d_is_shar_0f4ab6_idx'),
        ),
    ]
