# Generated by Django 5.2.10 on 2026-01-24 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='inference_d_is_shar_0f4ab6_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='sharing_mode',
            field=models.CharField(choices=[('private', 'Private'), ('shared_read', 'Shared (Read-Only)'), ('shared_write', 'Shared (Read/Write)')], default='private', help_text='Privacy setting for this document', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Deprecated: Use sharing_mode instead'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sharing_mode', 'status'], name='inference_d_sharing_aa8749_idx'),
        ),
    ]
