# Generated by Django 5.2.10 on 2026-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0004_remove_document_inference_d_is_shar_0f4ab6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('md', 'Markdown'), ('docx', 'Word Document'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
