# Generated by Django 5.2.10 on 2026-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0006_knowledgebase_document_knowledge_base'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgebase',
            new_name='inference_k_user_id_9ba3d7_idx',
            old_name='inference_k_user_id_is_default_idx',
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(default='Qwen/Qwen3-Embedding-0.6B', help_text='Embedding model used for this KB', max_length=100),
        ),
    ]
