# Generated by Django 5.2.13 on 2026-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0009_merge_extraction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='extractedrow',
            new_name='inference_e_schema__ecce45_idx',
            old_name='inference_extracted_row_schema_idx',
        ),
        migrations.RenameIndex(
            model_name='extractedrow',
            new_name='inference_e_schema__927012_idx',
            old_name='inference_extracted_row_schema_created_idx',
        ),
        migrations.RenameIndex(
            model_name='extractionschema',
            new_name='inference_e_user_id_e4f753_idx',
            old_name='inference_extraction_user_id_idx',
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(default='nvidia/nv-embedqa-e5-v5', help_text='Embedding model used for this KB', max_length=100),
        ),
    ]
