# Generated by Django 5.2.14 on 2026-08-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0010_rename_inference_extracted_row_schema_idx_inference_e_schema__ecce45_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='backend',
            field=models.CharField(choices=[('vector', 'Vector (semantic)'), ('fulltext', 'Keyword (exact / prefix match)'), ('raw', 'Raw (agent reads whole documents)'), ('hybrid', 'Hybrid (semantic + keyword)')], default='vector', help_text='Retrieval machinery this KB uses. Fixed once documents are ingested — switching would orphan whatever the old backend stored.', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('stored', 'Stored'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(default='nvidia/nv-embedqa-e5-v5', help_text='Embedding model used for this KB (vector/hybrid backends only)', max_length=100),
        ),
        migrations.CreateModel(
            name='IndexedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('term_frequency', models.IntegerField(default=1)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_hits', to='inference.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_hits', to='inference.document')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_terms', to='inference.knowledgebase')),
            ],
            options={
                'verbose_name': 'Indexed Term',
                'verbose_name_plural': 'Indexed Terms',
                'indexes': [models.Index(fields=['kb', 'term'], name='inference_i_kb_id_46fd46_idx'), models.Index(fields=['document'], name='inference_i_documen_44372e_idx')],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'term'), name='unique_term_per_chunk')],
            },
        ),
    ]
