# Generated by Django 5.2.14 on 2026-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0011_knowledgebase_backend_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_shared',
            field=models.BooleanField(default=False, help_text="Superseded by sharing_mode; kept as a mirror of (sharing_mode != 'private') for older clients that still read it. Maintained by Document.save(), never set independently — read sharing_mode in new code."),
        ),
    ]
