# Generated by Django 5.2.14 on 2026-09-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0014_document_folder_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('md', 'Markdown'), ('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('xlsx', 'Excel Workbook'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
