# Generated by Django 5.2.14 on 2026-09-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0017_publishedpage_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publishedpage',
            new_name='inference_p_is_list_be3973_idx',
            old_name='inference_p_is_liste_2b0e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='publishedpage',
            new_name='inference_p_owner_i_e0549c_idx',
            old_name='inference_p_owner_i_8c9d47_idx',
        ),
    ]
