# Generated by Django 5.2.14 on 2026-09-25 09:37

import django.db.models.deletion
import inference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0020_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('app', 'Edited in an app'), ('agent', 'Written by an agent'), ('restore', 'Before a restore')], default='app', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, default='', upload_to=inference.models.document_version_path)),
                ('content_text', models.TextField(blank=True, default='')),
                ('file_size', models.IntegerField(default=0)),
                ('spec', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inference.document')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='inference_d_documen_a00beb_idx')],
            },
        ),
    ]
