# Generated by Django 5.2.13 on 2026-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0021_document_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('md', 'Markdown'), ('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('xlsx', 'Excel Workbook'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('doc_legacy', 'Word 97–2003'), ('xls_legacy', 'Excel 97–2003'), ('ppt_legacy', 'PowerPoint 97–2003'), ('odt', 'OpenDocument Text'), ('ods', 'OpenDocument Spreadsheet'), ('odp', 'OpenDocument Presentation'), ('rtf', 'Rich Text'), ('zip', 'Zip Archive'), ('eml', 'Email'), ('other', 'Other')], max_length=10),
        ),
    ]
