# Generated by Django 5.2.14 on 2026-09-26 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0022_file_type_phase_f'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=32)),
                ('tabs', models.JSONField(blank=True, default=list)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'app'), name='inference_appsession_user_app_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RecentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='', max_length=32)),
                ('opened_at', models.DateTimeField()),
                ('open_count', models.PositiveIntegerField(default=1)),
                ('view_state', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_opens', to='inference.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
                'indexes': [models.Index(fields=['user', '-opened_at'], name='inf_recent_user_opened_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='inference_recent_user_document_uniq')],
            },
        ),
    ]
