# Generated by Django 5.2.14 on 2026-09-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(max_length=1000)),
                ('openapi_spec', models.JSONField(blank=True, default=dict)),
                ('auth', models.JSONField(blank=True, default=dict)),
                ('allowed_methods', models.JSONField(blank=True, default=list, help_text='Uppercase methods this connection may use. Empty: GET, HEAD.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'name'], name='data_apicon_user_id_cd2ed5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_api_connection_per_user')],
            },
        ),
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('bigquery', 'BigQuery'), ('sqlite', 'SQLite file in your workspace')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('host', models.CharField(blank=True, default='', max_length=253)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database', models.CharField(blank=True, default='', max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=200)),
                ('vfs_path', models.CharField(blank=True, default='', max_length=500)),
                ('ssl_mode', models.CharField(blank=True, default='', max_length=20)),
                ('allow_write', models.BooleanField(default=False, help_text='Offer execute_sql for this connection. Reads never need it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'kind'], name='data_dataco_user_id_d88cc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_data_connection_per_user')],
            },
        ),
    ]
