# Generated by Django 5.2.14 on 2026-09-21 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Registrable domain this profile belongs to, e.g. example.com', max_length=255)),
                ('provider_session_id', models.CharField(blank=True, default='', help_text='The provider-side session, when the engine supports reconnect', max_length=255)),
                ('live_url', models.URLField(blank=True, default='', help_text='Provider live-view URL, when one was offered', max_length=1000)),
                ('live_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired')], default='open', max_length=12)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Hard cap: the provider profile is dropped whatever is happening')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='browsing_br_user_id_38f51a_idx'), models.Index(fields=['user', 'domain', 'status'], name='browsing_br_user_id_d3b61a_idx')],
            },
        ),
    ]
