# Generated by Django 5.2.10 on 2026-02-26 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('search', 'Search'), ('image', 'Image Generation'), ('video', 'Video Generation'), ('workflow_suggestion', 'Workflow Suggestion'), ('workflow_result', 'Workflow Result'), ('system', 'System')], default='chat', max_length=30),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('text', 'Text File'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='chat.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
