# Generated by Django 5.2.10 on 2026-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='intent',
            field=models.CharField(default='chat', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('search', 'Search'), ('image', 'Image Generation'), ('video', 'Video Generation'), ('coding', 'Coding'), ('file_manipulation', 'File Manipulation'), ('workflow_suggestion', 'Workflow Suggestion'), ('workflow_result', 'Workflow Result'), ('system', 'System')], default='chat', max_length=30),
        ),
    ]
