# Generated by Django 5.2.10 on 2026-03-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_intent_alter_chatmessage_message_type'),
        ('inference', '0004_remove_document_inference_d_is_shar_0f4ab6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='inference_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_attachments', to='inference.document'),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='is_large_file',
            field=models.BooleanField(default=False),
        ),
    ]
