# Generated by Django 5.2.8 on 2026-07-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatattachment_inference_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(default='gemini-2.0-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='llm_provider',
            field=models.CharField(default='gemini', max_length=50),
        ),
    ]
