# Generated by Django 5.2.8 on 2026-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatsession_llm_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(default='nvidia/llama-3.3-nemotron-super-49b-v1', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='llm_provider',
            field=models.CharField(default='nvidia', max_length=50),
        ),
    ]
