# Generated by Django 5.2.8 on 2026-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatsession_llm_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='memory_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
