# Generated by Django 5.2.14 on 2026-08-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsession_memory_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(default='nvidia/nemotron-3-super-120b-a12b', max_length=100),
        ),
    ]
