# Generated by Django 5.2.14 on 2026-08-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatsession_llm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('disagreement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_exchanges', to='chat.chatattachment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_exchanges', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'attachment', 'created_at'], name='chat_vision_session_f04482_idx')],
            },
        ),
    ]
