# Generated by Django 5.2.14 on 2026-08-16 15:09

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_visionexchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolOutput',
            fields=[
                ('id', models.CharField(default=chat.models._tool_output_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('turn_id', models.CharField(blank=True, default='', max_length=64)),
                ('tool_name', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('total_chars', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_outputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'created_at'], name='chat_toolou_session_84e924_idx')],
            },
        ),
    ]
