# Generated by Django 5.2.14 on 2026-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_toolpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='llm_effort',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
