# Generated by Django 5.2.14 on 2026-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_session_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='llm_effort',
            field=models.CharField(blank=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='llm_model',
            field=models.CharField(default='openrouter/free', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='llm_provider',
            field=models.CharField(default='openrouter', max_length=50),
        ),
    ]
