# Generated by Django 5.2.14 on 2026-09-03 19:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_effort_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cached_read_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cached_write_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cost_source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='input_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='output_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='cost_source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12),
        ),
    ]
