# Generated by Django 5.2.14 on 2026-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_session_user_recent_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='paid_by',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='paid_by',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
