# Generated by Django 5.2.14 on 2026-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_record_who_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('docx', 'Word Document'), ('xlsx', 'Excel Workbook'), ('text', 'Text File'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
