# Generated by Django 5.2.14 on 2026-09-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_widen_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='autonomy',
            field=models.CharField(default='ask', max_length=10),
        ),
        migrations.AddField(
            model_name='toolpermission',
            name='match',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
