# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., OpenAI, Gmail, Slack)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique identifier for this credential type', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this credential is for')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('auth_method', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('custom', 'Custom')], default='api_key', max_length=20)),
                ('fields_schema', models.JSONField(default=list, help_text='JSON schema defining required credential fields')),
                ('oauth_config', models.JSONField(blank=True, default=dict, help_text='OAuth configuration (auth URL, token URL, scopes, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credential Type',
                'verbose_name_plural': 'Credential Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='credentials_slug_dc9193_idx'), models.Index(fields=['auth_method', 'is_active'], name='credentials_auth_me_9e023d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this credential', max_length=100)),
                ('encrypted_data', models.BinaryField(help_text='Encrypted credential data')),
                ('access_token', models.BinaryField(blank=True, help_text='Encrypted OAuth access token', null=True)),
                ('refresh_token', models.BinaryField(blank=True, help_text='Encrypted OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the credential has been verified to work')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if credential failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='credentials.credentialtype')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'credential_type'], name='credentials_user_id_3b7a56_idx'), models.Index(fields=['user', 'is_active'], name='credentials_user_id_082c05_idx'), models.Index(fields=['credential_type', 'is_active'], name='credentials_credent_b58679_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
