# Generated by Django 5.2.10 on 2026-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='public_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Public visibility credential data (username, urls, etc)'),
        ),
    ]
