# Generated by Django 5.2.10 on 2026-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_credentialauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='service_identifier',
            field=models.CharField(blank=True, help_text='Maps to nodeType (e.g., "openai", "gmail")', max_length=100, null=True, unique=True),
        ),
    ]
