# Generated by Django 5.2.14 on 2026-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_seed_credential_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialauditlog',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Name/type snapshot at event time; survives the credential being deleted'),
        ),
    ]
