# Generated by Django 5.2.10 on 2026-01-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('workflow_settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_test', 'Pending Test'), ('verified', 'Verified'), ('production', 'Production'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('success_rate', models.FloatField(default=0.0)),
                ('average_duration_ms', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('modifiable_fields', models.JSONField(blank=True, default=list)),
                ('is_cloneable', models.BooleanField(default=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('source_workflow_id', models.IntegerField(blank=True, help_text='ID of original workflow if auto-published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='templates.workflowtemplate')),
            ],
            options={
                'ordering': ['-usage_count', '-success_rate'],
            },
        ),
    ]
