# Generated by Django 5.2.10 on 2026-02-12 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'ordering': ['-is_featured', '-usage_count', '-average_rating']},
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='author_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='fork_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('devops', 'DevOps'), ('data', 'Data Pipeline'), ('support', 'Customer Support'), ('ai_ml', 'AI / ML'), ('sales', 'Sales'), ('hr', 'HR & Recruiting'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='TemplateComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='templates.templatecomment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='templates.workflowtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='templates.workflowtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('template', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='templates.workflowtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('template', 'user')},
            },
        ),
    ]
