# Generated by Django 5.2.14 on 2026-09-21 08:29

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('teams', 'Teams'), ('sms', 'SMS')], max_length=12)),
                ('label', models.CharField(blank=True, default='', help_text='Workspace, number or team name, for the picker', max_length=120)),
                ('credential_slug', models.CharField(blank=True, default='', help_text="Vault credential type holding this channel's tokens", max_length=100)),
                ('verified', models.BooleanField(default=False, help_text='The channel handshake completed (Slack OAuth, WhatsApp verification)')),
                ('secret', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=12)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null when the sender could not be attributed to an account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound', to='messaging.messagingaccount')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=12)),
                ('to', models.CharField(help_text='Channel id, phone number or handle sent to', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True)),
                ('cost_inr', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound', to='messaging.messagingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messagingaccount',
            index=models.Index(fields=['user', 'channel'], name='messaging_m_user_id_898922_idx'),
        ),
        migrations.AddIndex(
            model_name='messagingaccount',
            index=models.Index(fields=['secret'], name='messaging_m_secret_320252_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagingaccount',
            constraint=models.UniqueConstraint(fields=('user', 'channel', 'label'), name='unique_messaging_account_per_label'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['user', 'channel', '-received_at'], name='messaging_i_user_id_1542d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['account', '-received_at'], name='messaging_i_account_6085ed_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['user', 'channel', '-created_at'], name='messaging_o_user_id_bd74c9_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['user', 'status'], name='messaging_o_user_id_4e69c6_idx'),
        ),
    ]
