# Generated by Django 5.2.14 on 2026-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingaccount',
            name='channel',
            field=models.CharField(choices=[('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('teams', 'Teams'), ('sms', 'SMS'), ('telegram', 'Telegram')], max_length=12),
        ),
        migrations.AlterField(
            model_name='messagingaccount',
            name='verified',
            field=models.BooleanField(default=False, help_text='The channel handshake completed (Slack OAuth, WhatsApp verification, Telegram webhook)'),
        ),
    ]
