# Generated by Django 5.2.14 on 2026-09-21 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrator', '0024_template_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting'), ('paused', 'Paused'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('notebook_path', models.CharField(blank=True, default='', max_length=500)),
                ('budget_inr', models.IntegerField(default=0)),
                ('spent_inr', models.IntegerField(default=0)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('max_runs', models.IntegerField(default=20)),
                ('runs_done', models.IntegerField(default=0)),
                ('wait_for', models.JSONField(blank=True, default=dict)),
                ('next_wake_at', models.DateTimeField(blank=True, null=True)),
                ('last_report', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='orchestrator.subagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='missions_mi_user_id_078df3_idx'), models.Index(fields=['status', 'next_wake_at'], name='missions_mi_status_925bbf_idx')],
            },
        ),
    ]
