# Generated by Django 5.2.13 on 2026-04-27 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('motion_intensity', models.IntegerField(blank=True, null=True)),
                ('fps', models.IntegerField(blank=True, null=True)),
                ('voice', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('output_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
