# Generated by Django 5.2.13 on 2026-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='polling_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='output_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
