# Generated by Django 5.2.14 on 2026-08-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0003_imagineconversation_imaginemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='generate_audio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='output_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='quality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
