# Generated by Django 5.2.14 on 2026-09-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0004_generation_generate_audio_generation_output_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='background',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='batch_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='frame_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generation',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='output_compression',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='output_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generation',
            name='reference_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generation',
            name='response_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
