# Generated by Django 5.2.14 on 2026-09-21 08:12

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inference', '0019_widen_file_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='VFS path of the document, as the model named it', max_length=500)),
                ('signers', models.JSONField(default=list, help_text='[{name, email}] in signing order')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=12)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('secret', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, help_text='The file sent. Null if it has since been deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='inference.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='esign_signa_user_id_64ed5d_idx'), models.Index(fields=['secret'], name='esign_signa_secret_dec781_idx')],
            },
        ),
    ]
