# Generated by Django 5.2.14 on 2026-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_add_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='cache_write_price_per_million',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD per 1M cache-write tokens (blank = writes are free)', max_digits=10, null=True),
        ),
    ]
