# Generated by Django 5.2.14 on 2026-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_add_cache_write_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='default_effort',
            field=models.CharField(blank=True, default='', help_text='Effort level used when the caller names none (blank = provider default)', max_length=10),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='effort_levels',
            field=models.JSONField(blank=True, default=list, help_text='Reasoning-effort levels this model offers, e.g. ["low", "medium", "high"]. Empty = no effort control.'),
        ),
    ]
