# Generated by Django 5.2.13 on 2026-09-22 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_add_effort_levels'),
        ('orchestrator', '0024_template_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='replaced_by',
            field=models.CharField(blank=True, default='', help_text='Model value to suggest when this one is retired', max_length=150),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='source',
            field=models.CharField(choices=[('curated', 'Curated seed'), ('live', 'Live catalogue refresh'), ('hand', 'Hand-added')], default='curated', help_text='Which writer owns this row', max_length=12),
        ),
        migrations.CreateModel(
            name='ModelFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openrouter', max_length=30)),
                ('model', models.CharField(default='openrouter/free', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_fallback_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model fallback',
                'verbose_name_plural': 'Model fallback',
            },
        ),
        migrations.CreateModel(
            name='ModelFallbackNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.CharField(help_text='The retired llm_model value the owner was told about', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_notices', to='orchestrator.subagent')),
            ],
            options={
                'unique_together': {('subagent', 'old_value')},
            },
        ),
    ]
