# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this execution', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook'), ('api', 'API')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Input data passed to the workflow')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Final output from the workflow')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('error_node_id', models.CharField(blank=True, help_text='ID of the node that caused the error', max_length=100)),
                ('nodes_executed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tokens_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='ID of the node in the workflow', max_length=100)),
                ('node_type', models.CharField(help_text='Type of node (e.g., http_request, code, openai)', max_length=100)),
                ('node_name', models.CharField(blank=True, help_text='Display name of the node', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('execution_order', models.IntegerField(default=0, help_text='Order in which this node was executed')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Node configuration at execution time')),
                ('error_message', models.TextField(blank=True)),
                ('error_stack', models.TextField(blank=True, help_text='Stack trace if available')),
                ('retry_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Node Execution Log',
                'verbose_name_plural': 'Node Execution Logs',
                'ordering': ['execution_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(choices=[('approval', 'Approval Request'), ('clarification', 'Clarification Request'), ('error_recovery', 'Error Recovery'), ('credential_access', 'Credential Access'), ('workflow_modify', 'Workflow Modification'), ('admin_action', 'Admin Action'), ('api_access', 'API Access')], max_length=30)),
                ('request_details', models.JSONField(default=dict, help_text='Details of what was requested/asked')),
                ('response', models.JSONField(blank=True, default=dict, help_text='User response or action taken')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to respond in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Entry',
                'verbose_name_plural': 'Audit Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
