# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('orchestrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='orchestrator.workflow'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='orchestrator.workflow'),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='logs.executionlog'),
        ),
        migrations.AddField(
            model_name='nodeexecutionlog',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_logs', to='logs.executionlog'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['execution_id'], name='logs_execut_executi_39161f_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['workflow', '-created_at'], name='logs_execut_workflo_71c108_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['user', '-created_at'], name='logs_execut_user_id_f65ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['status', '-created_at'], name='logs_execut_status_c3e937_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['trigger_type', '-created_at'], name='logs_execut_trigger_c6eaa7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['user', '-created_at'], name='logs_audite_user_id_ec7f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['workflow', '-created_at'], name='logs_audite_workflo_ee038c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['action_type', '-created_at'], name='logs_audite_action__4e2166_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['-created_at'], name='logs_audite_created_64bfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['execution', 'node_id'], name='logs_nodeex_executi_f98217_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['execution', 'status'], name='logs_nodeex_executi_a8d207_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeexecutionlog',
            index=models.Index(fields=['node_type', 'status'], name='logs_nodeex_node_ty_548577_idx'),
        ),
    ]
