# Generated by Django 5.2.10 on 2026-01-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='is_subworkflow_execution',
            field=models.BooleanField(default=False, help_text='Flag to identify subworkflow executions'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='loop_iterations',
            field=models.IntegerField(default=0, help_text='Count of loops within this execution'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='nesting_depth',
            field=models.IntegerField(default=0, help_text='Depth in the execution hierarchy (0 = root)'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='parent_execution',
            field=models.ForeignKey(blank=True, help_text='Parent execution if this is a subworkflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_executions', to='logs.executionlog'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='timeout_budget_ms',
            field=models.IntegerField(blank=True, help_text='Allocated timeout budget in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='workflow_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of workflow definition at execution time'),
        ),
        migrations.AddField(
            model_name='nodeexecutionlog',
            name='child_execution',
            field=models.ForeignKey(blank=True, help_text='Link to the subworkflow execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_node_log', to='logs.executionlog'),
        ),
        migrations.AddField(
            model_name='nodeexecutionlog',
            name='input_mapping_applied',
            field=models.JSONField(blank=True, default=dict, help_text='Input variable mapping applied'),
        ),
        migrations.AddField(
            model_name='nodeexecutionlog',
            name='is_subworkflow_node',
            field=models.BooleanField(default=False, help_text='Whether this node executed a subworkflow'),
        ),
        migrations.AddField(
            model_name='nodeexecutionlog',
            name='output_mapping_applied',
            field=models.JSONField(blank=True, default=dict, help_text='Output variable mapping applied'),
        ),
    ]
