# Generated by Django 5.2.10 on 2026-02-22 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_executionlog_is_subworkflow_execution_and_more'),
        ('orchestrator', '0008_alter_workflow_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratorThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('workflow', 'Workflow Execution'), ('idle', 'Idle Reflection'), ('system', 'System Context')], default='workflow', max_length=20)),
                ('thought_type', models.CharField(choices=[('thinking', 'Internal Technical Reasoning'), ('thought', 'Concise Decision/Observation'), ('narrative', 'Synthesized Run Narrative'), ('status', 'Operational Status')], default='thought', max_length=20)),
                ('content', models.TextField(help_text='The core thought or concisely stated observation.')),
                ('reasoning', models.TextField(blank=True, help_text="Detailed internal technical reasoning or 'thinking' block.")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestrator_thoughts', to='logs.executionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestrator_thoughts', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestrator_thoughts', to='orchestrator.workflow')),
            ],
            options={
                'verbose_name': 'Orchestrator Thought',
                'verbose_name_plural': 'Orchestrator Thoughts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='logs_orches_user_id_7f46f3_idx'), models.Index(fields=['execution', 'thought_type'], name='logs_orches_executi_1b7e80_idx'), models.Index(fields=['category', '-created_at'], name='logs_orches_categor_2d2482_idx')],
            },
        ),
    ]
