# Generated by Django 5.2.10 on 2026-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_orchestratorthought'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestratorthought',
            name='node_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
