# Generated by Django 5.2.10 on 2026-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_orchestratorthought_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='supervision_level',
            field=models.CharField(blank=True, help_text='Level of orchestrator supervision used for this execution', max_length=20),
        ),
        migrations.AddField(
            model_name='orchestratorthought',
            name='model_id',
            field=models.CharField(blank=True, help_text='Technical ID of the model used', max_length=255),
        ),
        migrations.AddField(
            model_name='orchestratorthought',
            name='model_name',
            field=models.CharField(blank=True, help_text='Human-readable name of the model', max_length=255),
        ),
    ]
