# Generated by Django 5.2.14 on 2026-08-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_keyset_pagination_indexes'),
        ('orchestrator', '0017_add_subagent_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='subagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='orchestrator.subagent'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='subagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='orchestrator.subagent'),
        ),
        migrations.AddField(
            model_name='orchestratorthought',
            name='subagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestrator_thoughts', to='orchestrator.subagent'),
        ),
    ]
