# Generated by Django 5.2.14 on 2026-08-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_backfill_subagent_fk'),
        ('orchestrator', '0017_add_subagent_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='orchestrator.workflow'),
        ),
    ]
