# Generated by Django 5.2.14 on 2026-08-18 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_workflow_nullable'),
        ('orchestrator', '0018_add_trigger_and_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditentry',
            name='logs_audite_workflo_ee038c_idx',
        ),
        migrations.RemoveIndex(
            model_name='executionlog',
            name='logs_execut_workflo_71c108_idx',
        ),
        migrations.RemoveIndex(
            model_name='executionlog',
            name='logs_execut_workflo_9d79e3_idx',
        ),
        migrations.RemoveField(
            model_name='auditentry',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='orchestratorthought',
            name='workflow',
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['subagent', '-created_at'], name='logs_audite_subagen_441485_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['subagent', '-created_at'], name='logs_execut_subagen_a30235_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['subagent', '-created_at', '-id'], name='logs_execut_subagen_5b6256_idx'),
        ),
    ]
