# Generated by Django 5.2.14 on 2026-08-19 10:50

"""
Drop everything in `logs` that belonged to the DAG product.

Two whole tables: `AuditEntry` and `OrchestratorThought`. Neither had a writer
left anywhere in the codebase - the four read-only endpoints over them served
permanently-empty data, and two of those 500'd on a stale `workflow` FK. The
subworkflow columns on `ExecutionLog` / `NodeExecutionLog` go for the same
reason: nothing has set them since the node graph was retired.

The remaining `AlterField` operations are help_text edits only, and are no-ops
against the database.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_remove_auditentry_logs_audite_workflo_ee038c_idx_and_more'),
    ]

    operations = [
        # `AuditEntry` and `OrchestratorThought` are dropped whole; their FK
        # columns need no separate RemoveField, and issuing one on SQLite would
        # remake the table and try to rebuild indexes over the removed column.
        migrations.RemoveField(
            model_name='executionlog',
            name='is_subworkflow_execution',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='loop_iterations',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='nesting_depth',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='parent_execution',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='timeout_budget_ms',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='workflow_snapshot',
        ),
        migrations.RemoveField(
            model_name='nodeexecutionlog',
            name='child_execution',
        ),
        migrations.RemoveField(
            model_name='nodeexecutionlog',
            name='input_mapping_applied',
        ),
        migrations.RemoveField(
            model_name='nodeexecutionlog',
            name='is_subworkflow_node',
        ),
        migrations.RemoveField(
            model_name='nodeexecutionlog',
            name='output_mapping_applied',
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the run failed'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='error_node_id',
            field=models.CharField(blank=True, help_text='ID of the step that caused the error', max_length=100),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='input_data',
            field=models.JSONField(blank=True, default=dict, help_text='Input data passed to the run'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='output_data',
            field=models.JSONField(blank=True, default=dict, help_text='Final output from the run'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='supervision_level',
            field=models.CharField(blank=True, help_text='Level of supervision used for this run', max_length=20),
        ),
        migrations.AlterField(
            model_name='nodeexecutionlog',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Step configuration at execution time'),
        ),
        migrations.AlterField(
            model_name='nodeexecutionlog',
            name='execution_order',
            field=models.IntegerField(default=0, help_text='Order in which this step ran'),
        ),
        migrations.AlterField(
            model_name='nodeexecutionlog',
            name='node_id',
            field=models.CharField(help_text='ID of the step within the run', max_length=100),
        ),
        migrations.AlterField(
            model_name='nodeexecutionlog',
            name='node_name',
            field=models.CharField(blank=True, help_text='Display name', max_length=200),
        ),
        migrations.AlterField(
            model_name='nodeexecutionlog',
            name='node_type',
            field=models.CharField(help_text='Kind of step (for agent runs, the tool name)', max_length=100),
        ),
        migrations.DeleteModel(
            name='AuditEntry',
        ),
        migrations.DeleteModel(
            name='OrchestratorThought',
        ),
    ]
