# Generated by Django 5.2.14 on 2026-08-19 11:18

"""
The turn becomes a record, and so does the configuration a run executed under.

`AgentTurn` is one row per model call — the unit an agent actually works in.
It was previously reconstructed at read time by grouping `AgentStep.config`
(`{iteration, thought}`), which meant the grouping could not be queried and the
reasoning was a 150-character slice.

`SubAgentRevision` snapshots the flat AgentConfig the builder speaks, and
`ExecutionLog.revision` pins each run to the one it ran under.

The delegation columns on `ExecutionLog` point at the *step* that asked for the
run rather than the run that contained it, so the orchestrator's reasoning is
one hop away (`parent_step.turn.reasoning`).

`AgentStep.config` is deliberately still here — 0015 reads it, 0016 drops it.
"""

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_rename_nodeexecutionlog_to_agentstep'),
        ('orchestrator', '0019_remove_conversationmessage_workflow_delete_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='1-based, per agent')),
                ('config', models.JSONField(default=dict, help_text='Full AgentConfig snapshot at this revision')),
                ('diff', models.JSONField(blank=True, default=dict, help_text="{field: {'from': …, 'to': …}} against the previous revision")),
                ('summary', models.CharField(blank=True, help_text='Human-scannable list of what changed, e.g. "model, autonomy"', max_length=300)),
                ('source', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('backfill', 'Backfilled')], default='update', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sub-agent revision',
                'verbose_name_plural': 'Sub-agent revisions',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='executionlog',
            name='caller',
            field=models.CharField(choices=[('api', 'Direct API'), ('chat', 'Chat agent'), ('orchestrator', 'Delegated by another agent'), ('trigger', 'Trigger')], default='api', max_length=20),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='delegation_index',
            field=models.IntegerField(default=0, help_text='Position within the fan-out that produced this run'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='delegation_task',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='depth',
            field=models.IntegerField(default=0, help_text='Delegation depth; 0 is a run the user started'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='parent_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_runs', to='logs.agentstep'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='call_id',
            field=models.CharField(help_text="The provider's tool-call id", max_length=100),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='logs.executionlog'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='order',
            field=models.IntegerField(default=0, help_text='Position within the run; survives a resume'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='tool',
            field=models.CharField(help_text='Tool name, e.g. web_search', max_length=100),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='error_node_id',
            field=models.CharField(blank=True, help_text='call_id of the step that caused the error', max_length=100),
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='1-based, within the run')),
                ('reasoning', models.TextField(blank=True)),
                ('reasoning_truncated', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('content_truncated', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('tools', 'Called tools'), ('answer', 'Answered'), ('paused', 'Paused for approval'), ('error', 'Failed')], default='tools', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model_id', models.CharField(blank=True, max_length=200)),
                ('tokens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_ms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='logs.executionlog')),
            ],
            options={
                'verbose_name': 'Agent turn',
                'verbose_name_plural': 'Agent turns',
                'ordering': ['execution_id', 'index'],
            },
        ),
        migrations.AddField(
            model_name='agentstep',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='logs.agentturn'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['execution', 'call_id'], name='logs_agents_executi_f329d4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['execution', 'status'], name='logs_agents_executi_216520_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['execution', 'order'], name='logs_agents_executi_2ad10e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['turn', 'order'], name='logs_agents_turn_id_c2e179_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['tool', 'status'], name='logs_agents_tool_12da13_idx'),
        ),
        migrations.AddField(
            model_name='subagentrevision',
            name='subagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='orchestrator.subagent'),
        ),
        migrations.AddField(
            model_name='subagentrevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='logs.subagentrevision'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['caller', '-created_at'], name='logs_execut_caller_69c6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['parent_step', 'delegation_index'], name='logs_execut_parent__1549e0_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['revision', '-created_at'], name='logs_execut_revisio_28bcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentturn',
            index=models.Index(fields=['execution', 'index'], name='logs_agentt_executi_98e699_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentturn',
            unique_together={('execution', 'index')},
        ),
        migrations.AddIndex(
            model_name='subagentrevision',
            index=models.Index(fields=['subagent', '-number'], name='logs_subage_subagen_04019e_idx'),
        ),
        migrations.AddIndex(
            model_name='subagentrevision',
            index=models.Index(fields=['subagent', '-created_at'], name='logs_subage_subagen_cfdb69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subagentrevision',
            unique_together={('subagent', 'number')},
        ),
    ]
