# Generated by Django 5.2.14 on 2026-08-19 11:19

"""
Drop `AgentStep.config`, now that 0015 has read everything out of it.

It held `{iteration, thought}`: the turn grouping, which is now the `turn` FK,
and a 150-character slice of the model's reasoning, which is now `AgentTurn.
reasoning` in full. Nothing else ever went in it.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_backfill_turns_from_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentstep',
            name='config',
        ),
    ]
