# Generated by Django 5.2.14 on 2026-09-02 14:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_drop_step_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentturn',
            name='cached_read_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agentturn',
            name='cached_write_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agentturn',
            name='cost_source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='agentturn',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='agentturn',
            name='input_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agentturn',
            name='output_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='agentturn',
            name='reasoning_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='cached_read_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='cached_write_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='cost_source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='input_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='output_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
