# Generated by Django 5.2.14 on 2026-09-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_executionlog_thread_id'),
        ('orchestrator', '0023_alter_sharedagent_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='subagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='orchestrator.subagent'),
        ),
        migrations.AlterField(
            model_name='subagentrevision',
            name='subagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='orchestrator.subagent'),
        ),
    ]
