# Generated by Django 5.2.14 on 2026-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_keep_runs_after_agent_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagentrevision',
            name='source',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('backfill', 'Backfilled'), ('restore', 'Restored')], default='update', max_length=12),
        ),
    ]
