# Generated by Django 5.2.14 on 2026-09-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_revision_restore_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='caller',
            field=models.CharField(choices=[('api', 'Direct API'), ('chat', 'Chat agent'), ('orchestrator', 'Delegated by another agent'), ('trigger', 'Trigger'), ('eval', 'Evaluation sweep')], default='api', max_length=20),
        ),
    ]
