# Generated by Django 5.2.14 on 2026-09-19 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_record_who_paid'),
        ('logs', '0021_alter_executionlog_caller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='failure_category',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(help_text='+1 or -1')),
                ('reason', models.CharField(blank=True, default='', max_length=24)),
                ('comment', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatmessage')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='logs.executionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'indexes': [models.Index(fields=['user', '-created_at'], name='logs_feedba_user_id_e9026c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('chat_message__isnull', True), ('execution__isnull', False)), models.Q(('chat_message__isnull', False), ('execution__isnull', True)), _connector='OR'), name='logs_feedback_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('execution__isnull', False)), fields=('user', 'execution'), name='logs_feedback_unique_user_execution'), models.UniqueConstraint(condition=models.Q(('chat_message__isnull', False)), fields=('user', 'chat_message'), name='logs_feedback_unique_user_message')],
            },
        ),
        migrations.CreateModel(
            name='RunSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_session_id', models.CharField(blank=True, default='', max_length=100)),
                ('kind', models.CharField(max_length=24)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='chat.chatmessage')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='logs.executionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Run signal',
                'verbose_name_plural': 'Run signals',
                'indexes': [models.Index(fields=['user', 'kind', '-created_at'], name='logs_runsig_user_id_bf236f_idx')],
            },
        ),
    ]
