# Generated by Django 5.2.14 on 2026-09-21 06:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_widen_file_types'),
        ('logs', '0022_executionlog_failure_category_feedback_runsignal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image generation'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('browser', 'Browser minutes'), ('compute', 'Compute minutes'), ('transcription', 'Transcription'), ('esign', 'E-signature')], max_length=24)),
                ('units', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('amount_inr', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='', help_text='Tool or provider that produced the charge, e.g. generate_image', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_entries', to='logs.executionlog')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_entries', to='chat.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost entry',
                'verbose_name_plural': 'Cost entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='logs_costen_user_id_cfaac5_idx'), models.Index(fields=['execution', '-created_at'], name='logs_costen_executi_94a8f3_idx')],
            },
        ),
    ]
