# Generated by Django 5.2.14 on 2026-09-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0023_costentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstep',
            name='approval',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
