# Generated by Django 5.2.14 on 2026-09-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0024_agentstep_approval'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='caller',
            field=models.CharField(choices=[('api', 'Direct API'), ('chat', 'Chat agent'), ('orchestrator', 'Delegated by another agent'), ('trigger', 'Trigger'), ('eval', 'Evaluation sweep'), ('mission', 'Mission chain')], default='api', max_length=20),
        ),
    ]
