# Generated by Django 5.2.13 on 2026-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0025_executionlog_mission_alter_executionlog_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='fallback_from',
            field=models.CharField(blank=True, default='', help_text='Configured model value substituted away from, if any', max_length=150),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='model_used',
            field=models.CharField(blank=True, default='', help_text='Model value that served this run', max_length=150),
        ),
    ]
