# Generated by Django 5.2.10 on 2026-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
