# Generated by Django 5.2.14 on 2026-08-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='embedding',
        ),
    ]
