# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('node_start', 'Node Start'), ('node_complete', 'Node Complete'), ('node_error', 'Node Error'), ('workflow_start', 'Workflow Start'), ('workflow_complete', 'Workflow Complete'), ('workflow_error', 'Workflow Error'), ('hitl_request', 'HITL Request'), ('hitl_response', 'HITL Response'), ('progress', 'Progress Update'), ('thinking', 'AI Thinking'), ('planning', 'AI Planning'), ('log', 'Log Message')], max_length=30)),
                ('node_id', models.CharField(blank=True, help_text='Node ID if applicable', max_length=100)),
                ('data', models.JSONField(default=dict, help_text='Event data payload')),
                ('sequence', models.IntegerField(default=0, help_text='Sequence number for ordering events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='logs.executionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stream Event',
                'verbose_name_plural': 'Stream Events',
                'ordering': ['execution', 'sequence'],
                'indexes': [models.Index(fields=['event_id'], name='streaming_s_event_i_419511_idx'), models.Index(fields=['execution', 'sequence'], name='streaming_s_executi_1c0640_idx'), models.Index(fields=['execution', 'event_type'], name='streaming_s_executi_b5b88d_idx'), models.Index(fields=['user', '-created_at'], name='streaming_s_user_id_9d9967_idx')],
            },
        ),
    ]
