# Generated by Django 5.2.10 on 2026-01-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the node', max_length=100)),
                ('node_type', models.CharField(help_text='Unique identifier for the node type (e.g., custom_trello)', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('trigger', 'Trigger'), ('action', 'Action'), ('transform', 'Transform'), ('conditional', 'Conditional'), ('integration', 'Integration'), ('ai', 'AI/LLM'), ('utility', 'Utility')], default='action', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this node does')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for the node', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for the node in the editor', max_length=7)),
                ('code', models.TextField(help_text='Python code implementing the node handler')),
                ('fields_schema', models.JSONField(default=list, help_text='JSON schema defining node configuration fields')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='Expected input data schema')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='Output data schema')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether the code has passed validation')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors if any')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this node is available to other users')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Node',
                'verbose_name_plural': 'Custom Nodes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node_type'], name='nodes_custo_node_ty_eb51cb_idx'), models.Index(fields=['user', 'status'], name='nodes_custo_user_id_b329bb_idx'), models.Index(fields=['category', 'is_public'], name='nodes_custo_categor_35cf5b_idx'), models.Index(fields=['status', 'is_validated'], name='nodes_custo_status_19573a_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
