# Generated by Django 5.2.10 on 2026-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_aiprovider_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='supports_audio_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_audio_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_image_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_image_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_numeric_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_numeric_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_text_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_text_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_time_series_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_time_series_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_video_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_video_input',
            field=models.BooleanField(default=False),
        ),
    ]
