# Generated by Django 5.2.10 on 2026-03-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_aimodel_supports_audio_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='supports_document_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_document_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_embedding_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_structured_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_tabular_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_tabular_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_tool_calling',
            field=models.BooleanField(default=False),
        ),
    ]
