# Generated by Django 5.2.14 on 2026-08-13 19:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orchestrator', '0013_alter_workflow_llm_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('workflow_failed', 'Workflow Failed'), ('new_message', 'New Message'), ('hitl_request', 'Permission Required'), ('hitl_reminder', 'HITL Reminder'), ('hitl_digest', 'Daily HITL Digest'), ('image_ready', 'Image Generation Complete'), ('system', 'System Alert')], default='system', max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_notifications_enabled', models.BooleanField(default=True, help_text='Raise an OS-level notification for HITL nudges')),
                ('hitl_escalation_enabled', models.BooleanField(default=True, help_text='Nudge at +0, +1h and +1d for each unanswered request')),
                ('hourly_reminders_enabled', models.BooleanField(default=False, help_text='Also remind hourly while any request is still pending')),
                ('daily_digest_enabled', models.BooleanField(default=True)),
                ('daily_digest_time', models.TimeField(default=datetime.time(9, 0), help_text='Local wall-clock time to send the digest, in `timezone`')),
                ('timezone', models.CharField(blank=True, help_text="IANA timezone for digest/quiet hours; blank falls back to the user's profile", max_length=64)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(8, 0))),
                ('last_digest_sent_on', models.DateField(blank=True, help_text="Local date of the last digest; the hard 'one email per day' guard", null=True)),
                ('last_hourly_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='HITLReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=0, help_text='Index into STAGE_OFFSETS of the next nudge to send')),
                ('next_due_at', models.DateTimeField(blank=True, db_index=True, help_text='When the next nudge is due; NULL once exhausted or answered', null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hitl_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedule', to='orchestrator.hitlrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitl_reminder_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HITL Reminder Schedule',
                'verbose_name_plural': 'HITL Reminder Schedules',
                'ordering': ['next_due_at'],
                'indexes': [models.Index(fields=['next_due_at'], name='notificatio_next_du_09ac54_idx'), models.Index(fields=['user', 'next_due_at'], name='notificatio_user_id_0da812_idx')],
            },
        ),
    ]
