# Generated by Django 5.2.14 on 2026-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_notificationpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('workflow_failed', 'Workflow Failed'), ('new_message', 'New Message'), ('hitl_request', 'Permission Required'), ('hitl_reminder', 'HITL Reminder'), ('hitl_digest', 'Daily HITL Digest'), ('image_ready', 'Image Generation Complete'), ('system', 'System Alert'), ('agent_update', 'Agent Update')], default='system', max_length=50),
        ),
    ]
