# Generated by Django 5.2.13 on 2026-09-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('workflow_failed', 'Workflow Failed'), ('new_message', 'New Message'), ('hitl_request', 'Permission Required'), ('hitl_reminder', 'HITL Reminder'), ('hitl_digest', 'Daily HITL Digest'), ('image_ready', 'Image Generation Complete'), ('system', 'System Alert'), ('agent_update', 'Agent Update'), ('scheduled_reminder', 'Scheduled Reminder')], default='system', max_length=50),
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('repeat', models.CharField(choices=[('none', 'Once'), ('hourly', 'Every hour'), ('daily', 'Every day'), ('weekly', 'Every week')], default='none', max_length=10)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='When this fires next; NULL once spent or cancelled', null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('times_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['next_run_at'], name='notificatio_next_ru_cb1837_idx'), models.Index(fields=['user', 'next_run_at'], name='notificatio_user_id_d24016_idx')],
            },
        ),
    ]
