# Generated by Django 5.2.13 on 2026-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type_schedulednotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednotification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
