# Generated by Django 5.2.8 on 2026-07-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. invoice-extract-v3', max_length=200)),
                ('base_model', models.CharField(help_text='The model being tuned', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('training', 'Training'), ('completed', 'Completed'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('epochs_total', models.IntegerField(default=3)),
                ('epochs_done', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('baseline_accuracy', models.FloatField(blank=True, help_text='What the untuned base model scored on the same set', null=True)),
                ('cost_per_1k_paise', models.IntegerField(blank=True, help_text='Cost per 1k calls, in paise. Integer money — no float rounding.', null=True)),
                ('baseline_cost_per_1k_paise', models.IntegerField(blank=True, null=True)),
                ('tuned_model_id', models.CharField(blank=True, help_text='Provider id of the resulting model', max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(help_text='PROTECT: deleting the examples a deployed model was trained on would destroy the only record of why it behaves as it does', on_delete=django.db.models.deletion.PROTECT, related_name='tuning_jobs', to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuning_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tuning_tuni_user_id_40159a_idx'), models.Index(fields=['user', 'status'], name='tuning_tuni_user_id_926459_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
